### ISSUE TITLE
Update environment data storage for output

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/mineunit-actions#10]
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Starting **1st June 2023** workflows using save-state or set-output commands via stdout will fail with an error.

Previous way to store data to env:

```yaml
- name: Save state
  run: echo "::save-state name={name}::{value}"
- name: Set output
  run: echo "::set-output name={name}::{value}"
```

Should be updated to look something like this:

```yaml
- name: Save state
  run: echo "{name}={value}" >> $GITHUB_STATE
- name: Set output
  run: echo "{name}={value}" >> $GITHUB_OUTPUT
```
