### ISSUE TITLE
Test report details to comment and limit steps to certain events

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/mineunit-actions#5]
Demo: https://github.com/S-S-X/metatool/pull/100#issuecomment-787556806

Can be added to README.md but inclusion to action depends on #1 (actions in actions)

- [ ] Full report without too obstructing comments on pull request.
- [x] Update badges only when pushing (merging pull request) to master.
- [ ] Update report comments only when committing to pull request or opening pull request.

```yaml
    - uses: RubbaBoy/BYOB@v1.2.0
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        NAME: "${{ steps.mineunit-sharetool.outputs.badge-name }}"
        LABEL: "${{ steps.mineunit-sharetool.outputs.badge-label }}"
        STATUS: "${{ steps.mineunit-sharetool.outputs.badge-status }}"
        COLOR: "${{ steps.mineunit-sharetool.outputs.badge-color }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - if: success() && github.event_name == 'pull_request'
      uses: KeisukeYamashita/create-comment@v1
      with:
        check-only-first-line: true
        comment: |
          <details><summary><i>Click for detailed source code test coverage report</i></summary>
          
          ### Test coverage report for Metatool API sources:
          ```
          File                             Hits Missed Coverage
          -----------------------------------------------------
          ${{ steps.mineunit-metatool.outputs.mineunit-report }}
          ```
          ### Test coverage report for Containertool sources:
          ```
          File                             Hits Missed Coverage
          -----------------------------------------------------
          ${{ steps.mineunit-containertool.outputs.mineunit-report }}
          ```
          ### Test coverage report for Sharetool sources:
          ```
          File                             Hits Missed Coverage
          -----------------------------------------------------
          ${{ steps.mineunit-sharetool.outputs.mineunit-report }}
          ```
          </details>
```
